---
- include_role:
    name:               "{{ dependency }}"
  with_items:           "{{ platform_roles }}"
  loop_control:
    loop_var:           "dependency"
  when:                 skipdeps is not defined and platform_roles is defined
