---
- include:              '../tasks/dependencies.yml'
- include:              '../tasks/depend_on_platform.yml'
- include:              '../tasks/install_packages.yml'
- include:              '../tasks/install_files.yml'
- include:              '../tasks/template_files.yml'
- include:              'check_log.yml'
- include:              'run_updates.yml'
  when:                 install_files_result.changed
                        or check_log_result.changed
