---
- include:              '../tasks/dependencies.yml'
- include:              'platform_roles.yml'
- include:              '../tasks/symlinks.yml'
# 2021-02-16:  Package 'ntp' is not found until source lists are updated, for
# jetson_nano platform, with Ubuntu stock image.
- include:              '../tasks/install_files.yml'
- include:              '../tasks/remove_files.yml'
- include:              '../tasks/template_files.yml'
- command:              apt update
  become:               true
  changed_when:         False
- include:              '../tasks/install_packages.yml'
- include:              'stop_ua_service.yml'
- include:              '../tasks/remove_packages.yml'
- include:              'check_log.yml'
#- include:              'run_updates.yml'
- assert:
    that:               True
    quiet:              True
  changed_when:         True
  when:                 install_files_result.changed
                        or 0 != check_log_result.rc
  notify:               'run updates'
