---
- name:                 'platform roles'
  include_role:
    name:               "{{ platform_role }}"
# https://github.com/ansible/ansible/issues/82796
#  register:             platform_roles_result
  with_items:           "{{ platform_roles }}"
  loop_control:
    loop_var:           "platform_role"
  when:                 platform_roles is defined
