---
# This task succeeds if the OS update routine is launched regardless of whether
# the routine is successful.
- name:                 'run updates'
  shell:                '/usr/local/bin/update_debian_cronjob'
  retries:              3
  register:             run_updates_result
  changed_when:         False
